# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bc267d4fc2f82f7c2935300db109ec0b7a369aba97977cf9650a523a16ae3f55218f57258633c571aeb5a4a0ae629c8051b635bf2fcdac829f98a7a8fcbda414

test:
  secret_key_base: 3e118378be1327e0a5e6fcf1b0d994745bb84b1bf542e38900a5c8245e131b25a1dba0586105e46c1c1cfbe5d5e338e5400a3aad9d2222c62d946aaf2304a400

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
